version: '2'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - nodeops
    ports:
      - 443:443
      - 80:80
  nodeops:
    build: ./node
    container_name: nodeops
